---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dvm33ugq28ol/public_html/
    - export REPOPATH=/home/dvm33ugq28ol/repositories/website
    # Remove previous old files, if any.
    - /bin/rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory.
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    # Copy files from the repo main file
    - /bin/cp -R ${REPOPATH} ${DEPLOYPATH}

