---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dvm33ugq28ol/public_html/
    - export REPOPATH=/home/dvm33ugq28ol/repositories/website/main/
    # copy repo files into the deploy path
    - /bin/cp -R ${REPOPATH}* ${DEPLOYPATH}

